roles:
- role_name: datalake-sample
  create_role: false
  create_instance_profile: false         
  trusted_role_arns: []
  trusted_role_services: ["ec2.amazonaws.com"]
  policy:
  - allowed_actions:
    - s3:*
    resources:
    - "*"