roles:
- role_name: dynamodb-dax
  create_role: false
  create_instance_profile: false
  trusted_role_arns: []
  trusted_role_services: ["dax.amazonaws.com"]
  policy:
  - allowed_actions:
    - "dynamodb:DescribeTable"
    - "dynamodb:PutItem"
    - "dynamodb:GetItem"
    - "dynamodb:UpdateItem"
    - "dynamodb:DeleteItem"
    - "dynamodb:Query"
    - "dynamodb:Scan"
    - "dynamodb:BatchGetItem"
    - "dynamodb:BatchWriteItem"
    - "dynamodb:ConditionCheckItem"
    sid: DynamoDB
    resources:
    - "*"
- role_name: sns-logging
  create_role: true
  create_instance_profile: false         
  trusted_role_arns: []
  trusted_role_services: ["sns.amazonaws.com"]
  policy:
  - allowed_actions:
    - "logs:CreateLogGroup"
    - "logs:CreateLogStream"
    - "logs:PutLogEvents"
    - "logs:PutMetricFilter"
    - "logs:PutRetentionPolicy"
    sid: SNSLogging
    resources:
    - "*"
- role_name: apigw-logging
  create_role: true
  create_instance_profile: false         
  trusted_role_arns: []
  trusted_role_services: ["apigateway.amazonaws.com"]
  policy:
  - allowed_actions:
    - "logs:CreateLogGroup"
    - "logs:CreateLogStream"
    - "logs:PutLogEvents"
    - "logs:GetLogEvents"
    - "logs:DescribeLogGroups"
    - "logs:DescribeLogStreams"
    - "logs:FilterLogEvents"
    sid: AllowAPIGatwayToCloudwatch
    resources:
    - "*"

    
    