apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azdevops-scaledjob
  namespace: azure-agent
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: azdevops-agent-job
          image: "${azure_agent_image_uri}"
          imagePullPolicy: IfNotPresent
          env:
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azure-agent-secret
                key: AZP_URL
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azure-agent-secret
                key: AZP_POOL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azure-agent-secret
                key: AZP_TOKEN
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
          - mountPath: /aws_config
            name: awsconfig-volume
          - mountPath: /mnt/secrets-store
            name: secrets-store-inline
            readOnly: true
        serviceAccountName: azure-agent-sa
        volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "hmcl-cv-azure-agent-spc"
        - name: awsconfig-volume
          configMap:
            name: awsconfig-configmap
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: ${azure_agent_replica_max_count}   
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "${azure_agent_pool_id}"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"
    
